server:
  port: ${PORT:8080}
  ssl:
    enabled: false

api:
  version: @apiVersion@

logging:
  level:
    com.czertainly.utils: ${LOG_LEVEL:INFO}

management:
  endpoints:
    web:
      base-path: '/'
      exposure:
        include: health
      cors:
        allowed-origins: '*'
        allowed-methods: '*'
        allowed-headers: '*'
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  show-actuator: true