server:
  port: ${PORT:8080}
  ssl:
    enabled: false

logging:
  level:
    com.czertainly.utils: ${LOG_LEVEL:INFO}

management:
  endpoints:
    jmx:
      exposure:
        exclude: '*'
    web:
      base-path: '/'
      exposure:
        include: health, info