server:
  port: ${PORT:8080}
  ssl:
    enabled: false

api:
  version: @apiVersion@

logging:
  level:
    com.czertainly.utils: ${LOG_LEVEL:INFO}

management:
  endpoints:
    web:
      base-path: '/'
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true